### Config
@baseUrl = http://localhost:3001/api

### --- PRODUCTS ---
### Create Product 1
POST {{baseUrl}}/products
Content-Type: application/json

{
  "productName": "Laptop Dell XPS 15",
  "productType": "Electronics",
  "price": 2500
}

### Create Product 2
POST {{baseUrl}}/products
Content-Type: application/json

{
  "productName": "Mouse Logitech G502",
  "productType": "Accessories",
  "price": 50
}

### --- ORDERS (Cách 1: Tạo kèm sản phẩm) ---
### Create Order with Items
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "customerName": "John Doe",
  "status": "pending",
  "items": [
    {
      "productId": "c10ae264-a3e0-4e77-a709-9f6062f7c90e",
      "quantity": 1
    },
    {
      "productId": "855b6075-61d6-4196-80ed-60ae2b55a942",
      "quantity": 2
    }
  ]
}


### --- ORDER PRODUCTS (Cách 2: Thêm sản phẩm vào đơn đã có) ---

### Add Item to Existing Order
POST {{baseUrl}}/order-products
Content-Type: application/json

{
  "orderId": "dbc53067-61df-428e-951b-32e50a109ba2",
  "productId": "855b6075-61d6-4196-80ed-60ae2b55a942",
  "quantity": 5
}

### Get Order Detail (Để xem tổng tiền tự cập nhật)
GET {{baseUrl}}/orders/dbc53067-61df-428e-951b-32e50a109ba2
