### Config
@baseUrl = http://localhost:3001/api

### --- 1. CUSTOMERS ---

### Create Customer
# @name createCustomer
POST {{baseUrl}}/customers
Content-Type: application/json

{
  "name": "Nguyen Van A",
  "email": "customer_a1@example.com",
  "phone": "0987654321",
  "address": "Ha Noi, Viet Nam"
}

### Get All Customers
GET {{baseUrl}}/customers


### --- 2. PRODUCTS ---

### Create Product
# @name createProduct
POST {{baseUrl}}/products
Content-Type: application/json

{
  "productName": "Iphone 15 Pro Max",
  "productType": "Smartphone",
  "price": 1200
}


### --- 3. ORDERS (Gán Customer & Thêm sản phẩm) ---

### Create Order with Customer and Products
# Thay thế customerId và productId bằng ID thật từ các bước trên
POST {{baseUrl}}/orders
Content-Type: application/json

{
  "customerName": "Nguyen Van A",
  "customerId": "f1c3a37d-286b-4af2-a471-840586d345e0",
  "status": "pending",
  "products": [
    {
      "productId": "836658f6-415a-4f9d-ba93-acd6047c6080",
      "quantity": 2
    }
  ]
}

### Get Order Detail (Sẽ thấy Customer ID & Name)
GET {{baseUrl}}/orders/33edf8cf-4611-4e75-b572-f3e938bfa942


### --- 4. ORDER PRODUCTS (Cách 2: Thêm lẻ) ---

### Add Item to Existing Order
POST {{baseUrl}}/order-products
Content-Type: application/json

{
  "orderId": "REPLACE_WITH_ORDER_ID",
  "productId": "REPLACE_WITH_PRODUCT_ID",
  "quantity": 5
}
